### ISSUE TITLE
[BUG] Incorrect results for tracing indices and repeated indices

### ISSUE THREAD

**Issue by zhcui** [pyscf/pyscf-tblis#2]
Hi all,

I recently found that there seems to be a bug related to the following types of contraction with tblis,

Suppose you have installed pyscf-tblis.

1. 'ij, jk -> k' or 'ij, jk ->'
```
import numpy as np
from pyscf import lib

c = np.random.random((100, 100))
res_np = np.einsum("ij, jk -> k", c, c)
res_tblis = lib.einsum("ij, jk -> k", c, c)
print (np.linalg.norm(res_np - res_tblis)) # non-zero
```

2. 'iijk, kl -> jl'
```
import numpy as np
from pyscf import lib

d = np.random.random((2, 2, 100, 100))
c = np.random.random((100, 100))
res_np = np.einsum("iijk, kl -> jl", d, c)
res_tblis = lib.einsum("iijk, kl -> jl", d, c)
print (np.linalg.norm(res_np - res_tblis)) # non-zero

```
Should these types of contraction be supported by tblis? Could you take a look? Thanks!

Best,
Zhihao

**Comment by zhcui** [comment]
One fix is to change the numpy_helper in pyscf:
move the block of tblis to here:

```

    if ((not shared_idxAB) or  # Indices must overlap
        # repeated indices (e.g. 'iijk,kl->jl')
        len(idxA) != len(uniq_idxA) or len(idxB) != len(uniq_idxB)):
        return _numpy_einsum(idx_str, A, B)
    elif FOUND_TBLIS and C_dtype == numpy.double:
        # tblis is slow for complex type
        # ZHC NOTE tblis does not support reduction / repeated indices
        return tblis_einsum.contract(idx_str, A, B, **kwargs)
    elif uniq_idxA == shared_idxAB or uniq_idxB == shared_idxAB:
        # one operand is a subset of the other one (e.g. 'ijkl,jk->il')
        return _numpy_einsum(idx_str, A, B)
```

**Comment by fishjojo** [comment]
> One fix is to change the numpy_helper in pyscf: move the block of tblis to here:
> 
> ```
> 
>     if ((not shared_idxAB) or  # Indices must overlap
>         # repeated indices (e.g. 'iijk,kl->jl')
>         len(idxA) != len(uniq_idxA) or len(idxB) != len(uniq_idxB)):
>         return _numpy_einsum(idx_str, A, B)
>     elif FOUND_TBLIS and C_dtype == numpy.double:
>         # tblis is slow for complex type
>         # ZHC NOTE tblis does not support reduction / repeated indices
>         return tblis_einsum.contract(idx_str, A, B, **kwargs)
>     elif uniq_idxA == shared_idxAB or uniq_idxB == shared_idxAB:
>         # one operand is a subset of the other one (e.g. 'ijkl,jk->il')
>         return _numpy_einsum(idx_str, A, B)
> ```

@zhcui Please submit a PR, thanks.
